### ISSUE TITLE
Document as attachment

### ISSUE THREAD

**Issue by yujincheng08** [appleboy/telegram-action#22]
Can I send the document as attachment? I try to send a message with a document and it results in two separate messages: one for the text message itself and one for the document. Is it able to send them in one message?

**Comment by MrCarb0n** [comment]
Probably you've to use `message_file` instead of `message`.

**Comment by MrCarb0n** [comment]
this issue still exists?

**Comment by tetris-hermetris** [comment]
yep, it looks like it still exists
