### ISSUE TITLE
File too large error

### ISSUE THREAD

**Issue by Clashkid155** [appleboy/telegram-action#25]
I can't send 63mb file as document because file is too large

`Request Entity Too Large`

**Comment by GentlemanHu** [comment]
`Bots can currently send files of any type of up to 50 MB in size` from [Telegram FAQ](https://core.telegram.org/bots/faq#:~:text=Bots%20can%20currently%20send%20files,be%20changed%20in%20the%20future.)

**Comment by Clashkid155** [comment]
Thanks! Will close issue since it doesn't concern telegram-action.
