### ISSUE TITLE
add disable_notification option

### ISSUE THREAD

**Issue by vaaski** [appleboy/telegram-action#26]
[Telegram supports sending a message without notification](https://core.telegram.org/bots/api#sendmessage), however I don't see an option for that in the readme.

Can this be added?

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
try https://github.com/appleboy/telegram-action/releases/tag/v0.1.1 version

**Comment by vaaski** [comment]
seems to be working as expected.
