### ISSUE TITLE
Container action is only supported on Linux

### ISSUE THREAD

**Issue by whalemare** [appleboy/telegram-action#35]
Why we can't run it on self-hosted Mac OS?

**Comment by bhargav6744** [comment]
@whalemare any other workaround ?

**Comment by korsour** [comment]
still interested and need it to run on MacOS

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
try v1.0.0 version.

**Comment by walkinrey** [comment]
Run appleboy/telegram-action@v1.0.0
Error: Container action is only supported on Linux
