### ISSUE TITLE
Sending to group

### ISSUE THREAD

**Issue by ManuelSchneid3r** [appleboy/telegram-action#38]
I added secrets, added the [action](https://github.com/albertlauncher/albert/blob/master/.github/workflows/tg_notificatoins.yml), posted an issue and get [this error.](https://github.com/albertlauncher/albert/runs/3920376106?check_suite_focus=true)

Is posting to groups not supported?

**Comment by ManuelSchneid3r** [comment]
Ty works

**Comment by appleboy** [comment]
@ManuelSchneid3r You use the old tag. Please see the action page: https://github.com/marketplace/actions/telegram-message-notify the latest tag is `v0.1.1`

**Comment by ManuelSchneid3r** [comment]
I see thank you. I spent some hours to find out but no success so far. how can I send links to the github pull requests and issues?
