### ISSUE TITLE
Migrate from .hcl to .yml

### ISSUE THREAD

**Issue by Lukasss93** [appleboy/telegram-action#4]
Can you please migrate this action to yaml syntax?

Source: https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax

**Comment by appleboy** [comment]
@Lukasss93 Yes, I will update to the latest version asap. I have completed the `facebook-action` today.

https://github.com/appleboy/facebook-action

**Comment by appleboy** [comment]
https://github.com/marketplace/actions/telegram-message-notify release 0.0.4 version
