### ISSUE TITLE
Using personal account instead of bot

### ISSUE THREAD

**Issue by Clancyov** [appleboy/telegram-action#62]
hey. i wanted to know if there is any way to use my personal account instead of a bot account.
i have used telethone before. but my account needed verification and using actions i couldnt do that.

**Comment by yayahc** [comment]
No way @Clancyov as telegram allows messaging only through bot

**Comment by Clancyov** [comment]
> No way @Clancyov as telegram allows messaging only through bot

That is not true. I have used telethon lib in python and I sent massages with My personal account. But it needs authentication first time so I can not use it with GitHub actions.

**Comment by yayahc** [comment]
As you said, you need to be authenticated, so keep in mind that anyone with your Telegram user_id can send a message... and pretend to be you, which is one of the reasons why messaging services like Telegram or WhatsApp only allow messages to be sent using their API via a bot  (with bot_id).

**Comment by Clancyov** [comment]
yes im agree. but there are tokens and stuff too. if telegram (i dont know realy) gaved permission to use the hash id and token and phone number there werent any issue. but yes you are right the security is a very bold subject here.
