### ISSUE TITLE
##[error]Docker run failed with exit code 1

### ISSUE THREAD

**Issue by fragaLY** [appleboy/telegram-action#7]
See more there:

https://github.com/appleboy/telegram-action/commit/94223af513a61a65c31ae59a2936760e1a8ec421/checks?check_suite_id=346766069

**Comment by mashida** [comment]
> 
> 
> See more there:
> 
> https://github.com/appleboy/telegram-action/commit/94223af513a61a65c31ae59a2936760e1a8ec421/checks?check_suite_id=346766069

There is nothing left if I follow the link: 
![изображение](https://user-images.githubusercontent.com/34740100/77351277-9ac99400-6d4e-11ea-9dbf-167735114a9d.png)

Do you still have some specifics? @fragaLY

**Comment by fragaLY** [comment]
Right now, everything is Ok.

**Comment by fragaLY** [comment]
Could be closed.
